
Traceback (most recent call last):
  File "/home/pi/git/RPI_Projector/python_script/main.py", line 21, in <module>
    pr.ul.get_dir_path()
  File "/home/pi/git/RPI_Projector/python_script/usblistener.py", line 47, in get_dir_path
    self.lg("usblistener.py", "could not find dir_path in list %s; using default dir_path")
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/home/pi/git/RPI_Projector/python_script/main.py", line 21, in <module>
    pr.ul.get_dir_path()
  File "/home/pi/git/RPI_Projector/python_script/usblistener.py", line 47, in get_dir_path
    self.lg("usblistener.py", "could not find dir_path in list %s; using default dir_path")
AttributeError: LoggerWrapper instance has no __call__ method
Error: Can't open display: 
Traceback (most recent call last):
  File "/home/pi/git/RPI_Projector/python_script/main.py", line 27, in <module>
    time.sleep(0.3)
KeyboardInterrupt
Error: Can't open display: 
Traceback (most recent call last):
  File "/home/pi/git/RPI_Projector/python_script/main.py", line 27, in <module>
    time.sleep(0.3)
KeyboardInterrupt
Error: Can't open display: 
Traceback (most recent call last):
  File "/home/pi/git/RPI_Projector/python_script/main.py", line 27, in <module>
    time.sleep(0.3)
KeyboardInterrupt
Error: Can't open display: 
Traceback (most recent call last):
  File "/home/pi/git/RPI_Projector/python_script/main.py", line 27, in <module>
    time.sleep(0.3)
KeyboardInterrupt
Error: Can't open display: 
Traceback (most recent call last):
  File "/home/pi/git/RPI_Projector/python_script/main.py", line 27, in <module>
    time.sleep(0.3)
KeyboardInterrupt
